import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import vm from 'node:vm';import {ROOT,compile,loadTheme,embedAssets,LAYOUTS,contrast,wrap} from '../scripts/core.mjs';import {renderHTML} from '../scripts/html.mjs';
const theme=await loadTheme('neutral');const deck=s=>({version:1,title:'Test',sample:true,slides:[s]});
test('all worked examples compile with portable local assets',async()=>{let found=new Set();for(const file of (await fs.readdir(path.join(ROOT,'assets/examples'))).filter(x=>x.endsWith('.json'))){const d=JSON.parse(await fs.readFile(path.join(ROOT,'assets/examples',file)));const scene=await embedAssets(compile(d,await loadTheme(d.theme)),path.join(ROOT,'assets/examples'));const html=renderHTML(scene);for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);assert.equal(scene.slides.length,d.slides.length);d.slides.forEach(s=>found.add(s.layout));assert(!html.includes('NaN'));assert(scene.slides.every(s=>s.elements.every(n=>Number.isInteger(n.step))));}assert.deepEqual([...found].sort(),[...LAYOUTS].sort())});
test('negative bars and all-zero charts remain finite',()=>{for(const values of [[-20,0,30],[0,0,0]]){const s=compile(deck({layout:'bar',title:'Signed',unit:'h',data:values.map((value,i)=>({label:String(i),value}))}),theme);assert(s.slides[0].elements.every(e=>Number.isFinite(e.x+e.y+e.w+e.h)));assert(s.slides[0].elements.filter(e=>e.type==='rect').every(e=>e.h>=0))}});
test('waterfall totals are explicit and preserve signed labels',()=>{const s=compile(deck({layout:'waterfall',title:'Change',unit:'h',data:[{label:'Start',value:100,total:true},{label:'Less',value:-30},{label:'More',value:5},{label:'End',value:75,total:true}]}),theme);const txt=s.slides[0].elements.filter(e=>e.type==='text').map(e=>e.text);assert(txt.includes('-30'));assert(txt.includes('+5'));assert(txt.includes('75'))});
test('100 percent donut is a complete circle; zero total rejected',()=>{const d={layout:'donut',title:'Share',unit:'',data:[{label:'Only',value:5}]};assert(compile(deck(d),theme).slides[0].elements.some(e=>e.svg?.includes('<circle')));assert.throws(()=>compile(deck({...d,data:[{label:'Zero',value:0}]}),theme),/positive total/)});
test('invalid series cannot silently render a plausible graph',()=>{assert.throws(()=>compile(deck({layout:'stacked',title:'Mix',unit:'',series:['A','B'],data:[{label:'x',values:[2]}]}),theme),/mismatch/);assert.throws(()=>compile(deck({layout:'bar',title:'bad',unit:'',data:[{label:'x',value:'10'}]}),theme),/finite numeric/)});
test('excess copy produces a repairable error rather than clipping',()=>assert.throws(()=>compile(deck({layout:'statement',title:'長すぎる文章'.repeat(100)}),theme),/Shorten or change layout/));
test('ragged table and missing graph endpoint are rejected',()=>{assert.throws(()=>compile(deck({layout:'table',title:'Table',columns:['A','B'],rows:[[1]]}),theme),/ragged/);assert.throws(()=>compile(deck({layout:'architecture',title:'Graph',nodes:[{id:'a',x:100,y:300,w:200,h:90,label:'A'}],links:[{from:'a',to:'missing'}]}),theme),/unknown endpoint/)});
test('embedding source text cannot terminate the scene script',()=>{const s=compile(deck({layout:'statement',title:'Safe',notes:'</script><script>alert(1)</script>'}),theme);const html=renderHTML(s);assert(!html.includes('</script><script>alert'));const m=html.match(/id="slide-studio-scene">([\s\S]*?)<\/script>/);assert.equal(JSON.parse(m[1]).slides[0].notes,s.slides[0].notes)});
test('freeform rejects off-canvas, duplicate IDs and invalid colors',()=>{const base={layout:'freeform',title:'Custom',elements:[{type:'rect',id:'x',x:1200,y:200,w:100,h:100}]};assert.throws(()=>compile(deck(base),theme),/outside canvas/);const el={type:'rect',id:'x',x:100,y:200,w:100,h:100};assert.throws(()=>compile(deck({...base,elements:[el,el]}),theme),/duplicate element/);assert.throws(()=>compile(deck({...base,elements:[{...el,fill:'red;evil'}]}),theme),/invalid fill/)});
test('all themes keep primary text readable against background',async()=>{for(const file of (await fs.readdir(path.join(ROOT,'assets/themes')))){const t=await loadTheme(path.join(ROOT,'assets/themes',file));assert(contrast(t.paper,t.ink)>=7)}});
test('source provenance and build groups survive compilation',()=>{const s=compile(deck({layout:'process',title:'Steps',build:'sequential',notes:'Talk',sources:[{file:'input.csv'}],items:[{title:'A',body:'One'},{title:'B',body:'Two'}]}),theme).slides[0];assert.equal(s.sources[0].file,'input.csv');assert(s.elements.some(e=>e.step===1));assert(s.elements.some(e=>e.step===2));assert.equal(s.elements.find(e=>e.text==='Steps').step,0)});

test("Japanese punctuation does not start a wrapped line",()=>{for(const text of ["一つの論点を二つの視点から比較する。","画像の意味を説明し、読み手に次の行動を伝える。"]){const result=wrap(text,170,24);assert(!result.some(line=>/^[。、，．！？）］】」』]/.test(line)));}});
