/** Slide Studio: one measured scene -> HTML and editable presentation objects.
 * No model should manually maintain a chart label and a separate chart coordinate.
 * Layouts below calculate both from the same data. All geometry is CSS px (96 dpi).
 * Keep custom art in images; these primitives are for typography and information.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
export const ROOT=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
export const W=1280,H=720;
export const LAYOUTS=['cover','statement','section','agenda','split','metric','metrics','quote','comparison','table','bar','line','stacked','waterfall','donut','scatter','timeline','process','matrix','architecture','code','equation','image','closing','freeform'];
export const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const safeJSON=x=>JSON.stringify(x).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
export const assert=(v,msg)=>{if(!v)throw Error(msg)};
export function mix(a,b,t){return '#'+[1,3,5].map(i=>Math.round(parseInt(a.slice(i,i+2),16)*(1-t)+parseInt(b.slice(i,i+2),16)*t).toString(16).padStart(2,'0')).join('')}
export function contrast(a,b){const l=c=>[1,3,5].map(i=>parseInt(c.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);let x=l(a),y=l(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)}
export async function loadTheme(input='neutral'){const raw=typeof input==='object'?input:JSON.parse(await fs.readFile(input.endsWith('.json')?path.resolve(input):path.join(ROOT,'assets/themes',input+'.json'),'utf8'));const t={name:'Custom',paper:'#FFFFFF',ink:'#18212B',accent:'#2156CC',secondary:'#78869D',font:'Arial',headingFont:'Arial',radius:0,titleSize:48,bodySize:24,...raw};for(const k of ['paper','ink','accent','secondary'])assert(/^#[a-f\d]{6}$/i.test(t[k]),`theme.${k}: use #RRGGBB`);for(const k of ['font','headingFont'])assert(typeof t[k]==='string'&&/^[\p{L}\p{N} _,.-]+$/u.test(t[k]),`theme.${k}: use a plain font family name`);for(const k of ['radius','titleSize','bodySize'])assert(Number.isFinite(t[k])&&t[k]>=0,`theme.${k}: finite nonnegative number required`);t.muted=mix(t.ink,t.paper,.34);t.line=mix(t.ink,t.paper,.82);t.tint=mix(t.accent,t.paper,.92);return t}
// Predictable wrapping: English words stay together; CJK characters can wrap individually.
// The browser QA remeasures actual glyphs. This estimate is a guard, not a visual proof.
export function wrap(value,width,size){const measure=s=>[...s].reduce((n,c)=>n+(/[\u0000-\u00ff]/.test(c)?(/[MW@]/.test(c)?.86:/[il., :;!]/.test(c)?.3:.56):1)*size,0);return String(value).split('\n').flatMap(p=>{const tokens=p.match(/[A-Za-z0-9]+(?:[._%/-][A-Za-z0-9]+)*|[^A-Za-z0-9]/gu)||[''];let lines=[],cur='';for(const tok of tokens){if(cur&&measure(cur+tok)>width){if(/^[、。，．）)」』】〕〉》！？：；]/u.test(tok)){const tail=cur.match(/[A-Za-z0-9]+$/)?.[0]||[...cur].at(-1);lines.push(cur.slice(0,-tail.length).trimEnd());cur=tail+tok}else{let tail='';if(/[（(「『【〔〈《]$/u.test(cur)){tail=[...cur].at(-1);cur=cur.slice(0,-1)}lines.push(cur.trimEnd());cur=tail+tok.trimStart()}}else cur+=tok;if(measure(cur)>width){let rest=cur;cur='';for(const c of rest){if(cur&&measure(cur+c)>width){lines.push(cur);cur=''}cur+=c}}}lines.push(cur);return lines})}
function normalizeItems(v,min,max,name){assert(Array.isArray(v)&&v.length>=min&&v.length<=max,`${name}: expected ${min}–${max} items`);return v}
export function compile(spec,t){assert(spec&&spec.version===1,'deck.version must be 1');assert(typeof spec.title==='string'&&spec.title.trim(),'deck.title required');normalizeItems(spec.slides,1,120,'slides');const scenes=[];const warnings=[];
for(const [idx,s] of spec.slides.entries()){
 const where=`slide ${idx+1} (${s.layout})`;assert(LAYOUTS.includes(s.layout),`${where}: unknown layout`);assert(typeof s.title==='string'&&s.title.trim(),`${where}: title required`);
 const slide={id:s.id||'slide-'+(idx+1),title:s.title,layout:s.layout,paper:t.paper,notes:s.notes||'',sources:s.sources||[],elements:[],sample:!!spec.sample};let seq=0;const e=slide.elements;
 function text(value,x,y,w,h,size=t.bodySize,opts={}){assert(value!==undefined&&value!==null,`${where}: missing text`);const lines=wrap(value,w,size);const lineHeight=opts.lineHeight||1.3;assert(lines.length*size*lineHeight<=h+1,`${where}: text does not fit (${lines.length} lines): ${String(value).slice(0,55)}. Shorten or change layout.`);const n={type:'text',id:`n${++seq}`,x,y,w,h,size,font:opts.heading?t.headingFont:t.font,color:t.ink,weight:opts.heading?700:400,align:'left',text:lines.join('\n'),lineHeight,...opts};e.push(n);return n}
 function shape(type,x,y,w,h,opts={}){const n={type,id:`n${++seq}`,x,y,w,h,fill:t.tint,stroke:'none',strokeWidth:0,...opts};e.push(n);return n}
 function rule(x,y,w,color=t.line,width=1){return shape('line',x,y,w,0,{fill:'none',stroke:color,strokeWidth:width})}
 function segment(x,y,x2,y2,color=t.line,width=1){return shape('line',Math.min(x,x2),Math.min(y,y2),Math.abs(x2-x),Math.abs(y2-y),{x1:x,y1:y,x2,y2,fill:'none',stroke:color,strokeWidth:width})}
 const title=(txt=s.title)=>text(txt,72,76,1136,132,t.titleSize,{heading:true,lineHeight:1.15,maxLines:2});
 const kicker=txt=>text(txt,72,34,1100,28,15,{color:t.accent,weight:700});
 const body=(txt,x=72,y=224,w=1136,h=340)=>text(txt,x,y,w,h,t.bodySize,{color:t.muted});
 const bulletList=(items,x,y,w,step=74)=>normalizeItems(items,1,5,'items').forEach((it,i)=>{text(String(i+1).padStart(2,'0'),x,y+i*step,38,32,17,{color:t.accent,weight:700});text(typeof it==='string'?it:it.title,x+60,y+i*step,w-60,step-10,24)});
 const common=!['cover','statement','section','quote','closing'].includes(s.layout);
 if(common&&s.chrome!==false){if(s.kicker)kicker(s.kicker);title();}
 if(s.layout==='cover'){if(s.kicker)kicker(s.kicker);text(s.title,72,204,1090,240,72,{heading:true,lineHeight:1.15});if(s.body)body(s.body,76,483,1020,104);if(s.byline)text(s.byline,76,606,1050,32,17,{color:t.muted});}
 if(s.layout==='statement'){text(s.title,72,160,1136,340,76,{heading:true,lineHeight:1.2});if(s.body)body(s.body,76,542,1050,86);}
 if(s.layout==='section'){text(s.number||'01',72,176,370,240,170,{color:mix(t.accent,t.paper,.65),weight:700});text(s.title,474,237,730,204,54,{heading:true});if(s.body)body(s.body,478,472,700,100);}
 if(s.layout==='agenda'){bulletList(s.items,72,220,1050,79);}
 if(s.layout==='split'){text(s.leftTitle||'背景',72,232,470,86,32,{heading:true});body(s.leftBody,72,335,475,246);rule(619,224,0);shape('line',619,224,0,374,{stroke:t.line,strokeWidth:1});text(s.rightTitle||'示唆',697,232,510,86,32,{heading:true,color:t.accent});body(s.rightBody,697,335,510,246);}
 if(s.layout==='metric'){text(s.value,72,222,720,188,120,{weight:700,color:t.accent,lineHeight:1.1});text(s.label,78,438,700,90,32,{heading:true});if(s.body)body(s.body,872,258,330,284);if(s.baseline)text(s.baseline,78,563,1020,54,20,{color:t.muted});}
 if(s.layout==='metrics'){normalizeItems(s.items,2,4,'metrics');let cw=1136/s.items.length;for(const [i,it]of s.items.entries()){let x=72+i*cw;rule(x,238,cw-32,t.line,1);text(it.value,x,282,cw-30,104,58,{weight:700});text(it.label,x,408,cw-30,78,25,{heading:true});if(it.note)text(it.note,x,515,cw-32,75,19,{color:t.muted});}}
 if(s.layout==='quote'){text('“',67,93,130,134,140,{font:'Georgia',color:t.accent,lineHeight:.9});text(s.title,162,205,1000,277,52,{heading:true,lineHeight:1.35});if(s.attribution)text(s.attribution,168,535,980,64,21,{color:t.muted});}
 if(s.layout==='comparison'){normalizeItems(s.items,2,3,'comparison');let cw=1136/s.items.length;for(const [i,it] of s.items.entries()){const x=72+i*cw;rule(x,229,cw-36,i===s.highlight?t.accent:t.line,3);text(it.title,x,259,cw-34,88,32,{heading:true,color:i===s.highlight?t.accent:t.ink});text(it.body,x,374,cw-38,219,23,{color:t.muted});}}
 if(s.layout==='table'){const heads=normalizeItems(s.columns,2,6,'columns');const rows=normalizeItems(s.rows,1,6,'rows');rows.forEach(r=>assert(Array.isArray(r)&&r.length===heads.length,`${where}: ragged table`));let weights=s.widths||heads.map(()=>1);assert(weights.length===heads.length&&weights.every(v=>Number.isFinite(v)&&v>0),'table widths must be positive');const total=weights.reduce((a,b)=>a+b,0);let xs=[72];weights.forEach(v=>xs.push(xs.at(-1)+1136*v/total));let rh=Math.min(62,340/(rows.length+1));heads.forEach((h,j)=>text(h,xs[j]+10,229,xs[j+1]-xs[j]-20,rh-8,18,{weight:700,color:t.muted}));rule(72,220+rh,1136,t.ink,1.5);rows.forEach((r,i)=>{const yy=230+(i+1)*rh;if(i===s.highlight)shape('rect',72,yy-6,1136,rh,{fill:t.tint});r.forEach((v,j)=>text(String(v),xs[j]+10,yy,xs[j+1]-xs[j]-20,rh-8,20,{align:(s.numericColumns||[]).includes(j)?'right':'left'}));rule(72,yy+rh-7,1136)});}
 if(['bar','line','stacked','waterfall','scatter','donut'].includes(s.layout)){
  const data=normalizeItems(s.data,1,12,'chart data');assert(typeof s.unit==='string',`${where}: chart unit required (use '' for dimensionless)`);const palette=[t.accent,t.secondary,mix(t.accent,t.paper,.5),mix(t.ink,t.paper,.5)];
  const x0=132,y0=556,pw=1020,ph=294;const note=(v,x,y,w=100)=>text(String(v),x,y,w,30,17,{color:t.muted});
  if(s.layout==='donut'){assert(data.length<=5,'donut: max 5 parts');data.forEach(d=>assert(Number.isFinite(d.value)&&d.value>=0,'donut: nonnegative numeric values'));const sum=data.reduce((a,d)=>a+d.value,0);assert(sum>0,'donut: positive total required');let angle=-Math.PI/2;let segments='';for(const [i,d] of data.entries()){let end=angle+Math.PI*2*d.value/sum;const r=115,cx=170,cy=170,large=end-angle>Math.PI?1:0;if(d.value===sum)segments+=`<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${palette[i%4]}" stroke-width="38"/>`;else if(d.value>0)segments+=`<path d="M${cx+Math.cos(angle)*r} ${cy+Math.sin(angle)*r} A${r} ${r} 0 ${large} 1 ${cx+Math.cos(end)*r} ${cy+Math.sin(end)*r}" fill="none" stroke="${palette[i%4]}" stroke-width="38"/>`;angle=end;text(`${d.label}  ${+(d.value/sum*100).toFixed(1)}%`,731,248+i*66,470,55,25,{color:palette[i%4]});}shape('svg',185,227,340,340,{svg:`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 340 340" role="img" aria-label="${esc(data.map(d=>d.label+': '+d.value).join(', '))}">${segments}</svg>`});text(s.center||String(sum),215,363,280,90,43,{align:'center',weight:700});}
  else {
   const vals=s.layout==='stacked'?data.map(d=>{assert(Array.isArray(d.values)&&d.values.length>=1&&d.values.length<=4,'stacked: 1–4 series');d.values.forEach(v=>assert(Number.isFinite(v)&&v>=0,'stacked: nonnegative finite values'));return d.values.reduce((a,b)=>a+b,0)}):s.layout==='scatter'?data.map(d=>d.y):data.map(d=>d.value);
   vals.forEach(v=>assert(Number.isFinite(v),'chart: finite numeric data required'));
   let totals=[];if(s.layout==='waterfall'){let running=0;for(const d of data){const before=d.total?0:running;running=d.total?d.value:running+d.value;totals.push([before,running]);}}
   const all=s.layout==='waterfall'?totals.flat():vals;let lo=Math.min(0,...all),hi=Math.max(0,...all);if(lo===hi)hi=lo+1;const range=hi-lo;lo=lo<0?Math.floor(lo/(range/4))*(range/4):0;hi=hi>0?Math.ceil(hi/(range/4))*(range/4):0;const yy=v=>y0-(v-lo)/(hi-lo)*ph;
   for(let i=0;i<=4;i++){const v=lo+(hi-lo)*i/4;rule(x0,yy(v),pw,t.line);text(String(+v.toFixed(1)),72,yy(v)-10,48,26,15,{align:'right',color:t.muted})}note(s.unit,72,220,300);const step=pw/data.length;
   if(s.layout==='scatter'){const xv=data.map(d=>d.x);xv.forEach(v=>assert(Number.isFinite(v),'scatter: finite x values'));const xmin=Math.min(0,...xv),xmax=Math.max(1,...xv);data.forEach((d,i)=>{const x=x0+(d.x-xmin)/(xmax-xmin)*pw;shape('ellipse',x-7,yy(d.y)-7,14,14,{fill:t.accent});if(d.label)text(d.label,x+11,yy(d.y)-12,90,28,15,{color:t.muted})});[0,1,2,3,4].forEach(i=>text(String(+(xmin+(xmax-xmin)*i/4).toFixed(1)),x0+pw*i/4-30,577,60,28,15,{align:'center',color:t.muted}));note(s.xLabel||'X',1052,611,110);}
   else data.forEach((d,i)=>{const x=x0+i*step;const bw=Math.min(90,step*.6);text(d.label,x+3,582,step-6,49,16,{align:'center',color:t.muted});
    if(s.layout==='bar'){shape('rect',x+(step-bw)/2,Math.min(yy(d.value),yy(0)),bw,Math.abs(yy(d.value)-yy(0)),{fill:i===s.highlight?t.accent:mix(t.accent,t.paper,s.highlight===undefined?0:.6)});text(String(d.value),x,yy(d.value)-(d.value>=0?32:-6),step,28,18,{align:'center'});}
    if(s.layout==='line'){if(i)segment(x-step/2,yy(data[i-1].value),x+step/2,yy(d.value),t.accent,3);shape('ellipse',x+step/2-5,yy(d.value)-5,10,10,{fill:t.accent});text(String(d.value),x,yy(d.value)-32,step,28,17,{align:'center'});}
    if(s.layout==='stacked'){let sum=0;d.values.forEach((v,j)=>{sum+=v;shape('rect',x+(step-bw)/2,yy(sum),bw,ph*v/(hi-lo),{fill:palette[j]})});text(String(vals[i]),x,yy(vals[i])-32,step,28,17,{align:'center'});}
    if(s.layout==='waterfall'){const [a,b]=totals[i];shape('rect',x+(step-bw)/2,yy(Math.max(a,b)),bw,Math.abs(yy(a)-yy(b)),{fill:d.total?t.ink:d.value>=0?t.accent:t.secondary});if(i<data.length-1)rule(x+(step+bw)/2,yy(b),step-bw,t.line);text((!d.total&&d.value>0?'+':'')+d.value,x,yy(Math.max(a,b))-32,step,28,17,{align:'center'});}
   });
   if(s.layout==='stacked'){normalizeItems(s.series,1,4,'series');assert(data.every(d=>d.values.length===s.series.length),'stacked: series length mismatch');s.series.forEach((name,i)=>{shape('rect',650+i*139,218,12,12,{fill:palette[i]});text(name,670+i*139,211,113,35,16,{color:t.muted})});}
  }
 }
 if(s.layout==='timeline'){const items=normalizeItems(s.items,2,5,'timeline');const step=1040/(items.length-1);rule(108,364,1040,t.line,3);items.forEach((it,i)=>{const x=108+step*i;shape('ellipse',x-7,357,14,14,{fill:t.accent});text(it.date,Math.min(x-40,1018),285,Math.min(step-20,190),50,21,{weight:700});text(it.title,Math.min(x-40,1018),402,Math.min(step-20,190),110,22);if(it.body)text(it.body,Math.min(x-40,1018),523,Math.min(step-20,190),72,17,{color:t.muted})});}
 if(s.layout==='process'){const items=normalizeItems(s.items,2,4,'process');const step=1136/items.length;items.forEach((it,i)=>{const x=72+i*step;text(String(i+1).padStart(2,'0'),x,254,100,80,44,{color:t.accent,weight:700});rule(x,351,step-32,t.line,2);text(it.title,x,383,step-32,90,30,{heading:true});if(it.body)text(it.body,x,494,step-32,110,22,{color:t.muted})});}
 if(s.layout==='matrix'){normalizeItems(s.items,4,4,'matrix');s.items.forEach((it,i)=>{const x=110+(i%2)*550,y=235+Math.floor(i/2)*168;shape('rect',x,y,522,146,{fill:i===s.highlight?t.tint:mix(t.ink,t.paper,.97),radius:t.radius});text(it.title,x+24,y+16,472,64,27,{heading:true});text(it.body,x+24,y+86,472,47,20,{color:t.muted})});text(s.xLabel||'X →',777,600,390,35,18,{align:'right',color:t.muted});text(s.yLabel||'Y ↑',72,198,500,32,18,{color:t.muted});}
 if(s.layout==='architecture'){const nodes=normalizeItems(s.nodes,1,12,'nodes');const map=new Map(nodes.map(n=>[n.id,n]));assert(map.size===nodes.length,'duplicate node IDs');for(const link of s.links||[]){const a=map.get(link.from),b=map.get(link.to);assert(a&&b,'architecture: unknown endpoint');const ac=[a.x+a.w/2,a.y+a.h/2],bc=[b.x+b.w/2,b.y+b.h/2];const dx=bc[0]-ac[0],dy=bc[1]-ac[1];const edge=(n,c,sign)=>{const f=Math.min((n.w/2)/(Math.abs(dx)||1e-9),(n.h/2)/(Math.abs(dy)||1e-9));return [c[0]+sign*dx*f,c[1]+sign*dy*f]};const aa=edge(a,ac,1),bb=edge(b,bc,-1);segment(...aa,...bb,t.secondary,2);if(link.label)text(link.label,(aa[0]+bb[0])/2-70,(aa[1]+bb[1])/2-35,140,30,15,{align:'center',color:t.muted})}for(const n of nodes){shape('rect',n.x,n.y,n.w,n.h,{fill:n.accent?t.tint:t.paper,stroke:t.line,strokeWidth:1,radius:t.radius});text(n.label,n.x+16,n.y+18,n.w-32,n.h-28,22,{align:'center',weight:600})}}
 if(s.layout==='code'){shape('rect',72,224,722,388,{fill:t.ink,radius:t.radius});text(s.code,100,253,668,330,20,{font:'Consolas',color:t.paper,lineHeight:1.5});text(s.explanation,858,253,350,300,27,{color:t.muted});}
 if(s.layout==='equation'){text(s.equation,72,263,1136,162,60,{font:'Georgia',align:'center'});if(s.body)body(s.body,150,475,980,125);}
 if(s.layout==='image'){assert(s.src&&s.alt,'image requires src and meaningful alt');shape('image',72,216,658,410,{src:s.src,alt:s.alt,fit:s.fit||'cover'});text(s.body,792,237,416,344,29);}
 if(s.layout==='closing'){if(s.kicker)kicker(s.kicker);text(s.title,72,187,1100,250,68,{heading:true});if(s.body)body(s.body,76,486,1080,108);}
 if(s.layout==='freeform'){normalizeItems(s.elements,1,150,'elements');for(const n of s.elements){assert(['text','rect','ellipse','line','image','svg'].includes(n.type),'invalid freeform type');if(n.type==='text')text(n.text,n.x,n.y,n.w,n.h,n.size||24,n);else shape(n.type,n.x,n.y,n.w,n.h,n)}}
 // Reveal groups are explicit. Group 0 is visible immediately; static exports show all.
 for(const n of e)n.step??=0;
 if(s.reveal){assert(Array.isArray(s.reveal),'reveal must be a list of element IDs');for(const [i,id]of s.reveal.entries()){const n=e.find(n=>n.id===id);assert(n,`unknown reveal element ${id}`);n.step=i+1;}}
 if(s.build==='content')for(const n of e)if(n.y>=216&&n.y<640)n.step=1;
 if(s.build==='sequential'){let stages=[...new Set(e.filter(n=>n.y>=216&&n.y<640).map(n=>n.x))].sort((a,b)=>a-b);for(const n of e)if(n.y>=216&&n.y<640)n.step=stages.indexOf(n.x)+1;}
 if(s.chrome!==false&&spec.brand?.logo)shape('image',1088,25,120,42,{src:spec.brand.logo,alt:spec.brand.name||'Company logo',fit:'contain'});
 if(s.chrome!==false){rule(72,666,1136,t.line);text(spec.brand?.footer||spec.title,72,677,940,25,13,{color:t.muted});text(`${idx+1} / ${spec.slides.length}`,1095,677,113,25,13,{align:'right',color:t.muted});if(spec.sample)text('DEMO / 架空データ',936,spec.brand?.logo?638:38,272,24,13,{align:'right',color:t.muted});}
 assert(new Set(e.map(n=>n.id)).size===e.length,`${where}: duplicate element IDs`);for(const n of e){n.step??=0;for(const c of ['color','fill','stroke'])if(n[c]!==undefined)assert(n[c]==='none'||/^#[a-f\d]{6}$/i.test(n[c]),`${where}: invalid ${c}`);if(n.font)assert(/^[\p{L}\p{N} _,.-]+$/u.test(n.font),`${where}: invalid font`);assert(Number.isInteger(n.step)&&n.step>=0,`${where}: step must be a nonnegative integer`);for(const k of ['x','y','w','h'])assert(Number.isFinite(n[k]),`${where}: invalid ${n.id}.${k}`);assert(n.w>=0&&n.h>=0,`${where}: negative bounds`);assert(n.x>=0&&n.y>=0&&n.x+n.w<=W+1&&n.y+n.h<=H+1,`${where}: ${n.id} outside canvas`);}
 const supporting=e.filter(n=>n.type==='text'&&n.y<650&&n.y>65).map(n=>n.size);if(supporting.length&&Math.min(...supporting)<18)warnings.push(`${where}: supporting type reaches ${Math.min(...supporting)}px; review for viewing distance`);
 if(!s.sources?.length&&['bar','line','stacked','waterfall','scatter','donut','metric','metrics'].includes(s.layout)&&!spec.sample)warnings.push(`${where}: evidence source missing`);
 scenes.push(slide);
}
assert(new Set(scenes.map(s=>s.id)).size===scenes.length,'duplicate slide IDs');return {version:1,width:W,height:H,title:spec.title,language:spec.language||'ja',theme:t,slides:scenes,warnings};}
export async function embedAssets(scene,base){for(const s of scene.slides)for(const n of s.elements){if(n.type==='image'){assert(!/^https?:/i.test(n.src),'Download image sources locally first; remote fetch is not implicit');if(!n.src.startsWith('data:')){const bytes=await fs.readFile(path.resolve(base,n.src));const ext=path.extname(n.src).toLowerCase();const mime={'.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml'}[ext];assert(mime,'Unsupported image type');n.src=`data:${mime};base64,${bytes.toString('base64')}`}}if(n.type==='svg'){assert(typeof n.svg==='string'&&n.svg.includes('<svg'),'svg element requires svg markup');assert(!/<script|on\w+\s*=|<foreignObject|(?:href|src)\s*=\s*["'](?:https?:|javascript:)/i.test(n.svg),'Active/external SVG is not accepted');n.src='data:image/svg+xml;base64,'+Buffer.from(n.svg).toString('base64')}}return scene;}
