/** Trusted authored modules -> self-contained HTML. No framework, CDN or templates required. */
import fs from 'node:fs/promises';import path from 'node:path';import vm from 'node:vm';import {fileURLToPath} from 'node:url';
import {checkSlideCopy,visibleText,rules as copyRules} from './copy-core.mjs';
import {reviewCopy} from '../assets/runtime/editorial-review.mjs';
import {checkCss} from './css-check.mjs';
import {validateBrand,brandCSS,brandLogo} from './brand-core.mjs';
import {h,assert} from '../assets/runtime/kit.mjs';
export const ROOT=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const json=v=>JSON.stringify(v).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
const languages={en:['Previous','Next','Slide','Overview','Notes','Reset','Fullscreen'],ja:['前へ','次へ','スライド','一覧','ノート','リセット','全画面'],zh:['上一页','下一页','幻灯片','总览','备注','重置','全屏'],ko:['이전','다음','슬라이드','개요','노트','초기화','전체 화면'],ar:['السابق','التالي','الشريحة','نظرة عامة','ملاحظات','إعادة ضبط','ملء الشاشة'],de:['Zurück','Weiter','Folie','Übersicht','Notizen','Zurücksetzen','Vollbild'],fr:['Précédent','Suivant','Diapositive','Aperçu','Notes','Réinitialiser','Plein écran'],es:['Anterior','Siguiente','Diapositiva','Vista general','Notas','Restablecer','Pantalla completa'],pt:['Anterior','Seguinte','Slide','Visão geral','Notas','Repor','Tela cheia'],hi:['पिछला','अगला','स्लाइड','अवलोकन','नोट्स','रीसेट','पूर्ण स्क्रीन'],ru:['Назад','Далее','Слайд','Обзор','Заметки','Сброс','Полный экран'],it:['Indietro','Avanti','Diapositiva','Panoramica','Note','Ripristina','Schermo intero']};
export function validateCraft(deck,{allowDraft=false}={}){
 assert(deck&&typeof deck==='object','Default export must be a deck object.');assert(typeof deck.title==='string'&&deck.title.trim(),'deck.title is required.');
 const cssCheck=checkCss(deck.css||'');assert(cssCheck.passed,'CSS structure: '+cssCheck.issues.map(x=>`line ${x.line}, column ${x.column}: ${x.message}`).join('; '));
 assert(!deck.draft||allowDraft,'Author the real deck and set draft:false. --allow-draft is preview only.');
 assert(Array.isArray(deck.slides)&&deck.slides.length,'At least one authored slide is required.');
 if(deck.brand)validateBrand(deck.brand,{allowDraft:!!(allowDraft&&deck.draft)});
 assert(!deck.readingMode||['live','read','reference','hybrid'].includes(deck.readingMode),'readingMode must be live, read, reference or hybrid.');
 const copyFindings=[];
 const ids=new Set();for(const s of deck.slides){
  assert(!s.study||deck.mode==='workshop'||(deck.draft&&allowDraft),'Workshop example is not an audience deck. Derive real content and clear study only after authoring.');
  const findings=checkSlideCopy(s);copyFindings.push(...findings.map(f=>({...f,slide:s.id})));
  if(deck.mode!=='workshop'&&!(deck.draft&&allowDraft))assert(!findings.some(f=>f.level==='error'&&!f.waived),'Production instruction / placeholder in '+s.id+': '+findings.filter(f=>f.level==='error'&&!f.waived).map(f=>f.quote).join(', '));
 assert(/^[A-Za-z][\w-]*$/.test(s.id),'Stable slide ID required.');assert(!ids.has(s.id),'Duplicate slide ID: '+s.id);ids.add(s.id);assert(typeof s.title==='string'&&s.title.trim(),'Accessible slide title required.');assert(typeof s.content==='string'&&s.content.trim(),'Authored content is required.');assert(!/(?:NaN|Infinity)(?:px|[ ,;\"])/.test(s.content),'Nonfinite geometry in authored content.');assert(!/<script\b/i.test(s.content),'Use deck.script for trusted code, not embedded script tags.');}
 const width=deck.width||deck.brand?.canvas.width||1280,height=deck.height||deck.brand?.canvas.height||720;assert([width,height].every(n=>Number.isInteger(n)&&n>=240&&n<=8192),'Canvas dimensions must be integers, 240..8192.');
 assert(!deck.direction||['ltr','rtl'].includes(deck.direction),'direction must be ltr or rtl.');if(deck.script)new vm.Script(deck.script);
 return {valid:true,slides:deck.slides.length,draft:!!deck.draft,copyFindings,editorialReview:reviewCopy(deck.slides.map(s=>({id:s.id,title:s.title,body:visibleText(s.content.replace(/<h[1-6]\b[^>]*>[\s\S]*?<\/h[1-6]>/gi,' ')),language:s.language})),{language:deck.language||'en'}),deliveryApproved:false};
}
export async function embedAssets(content,base=ROOT){
 const matches=[...new Set([...content.matchAll(/\{\{asset:([^}]+)\}\}/g)].map(m=>m[1]))];
 for(const rel of matches){const file=path.resolve(base,rel);assert(file.startsWith(path.resolve(base)+path.sep),'Asset path escapes project.');const real=await fs.realpath(file),root=await fs.realpath(base);assert(real.startsWith(root+path.sep),'Symlink asset escapes project.');const data=await fs.readFile(real);assert(data.length<=16*1024*1024,'Asset exceeds 16 MiB; link/package large media deliberately.');const ext=path.extname(file).toLowerCase(),mime={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.webm':'video/webm','.mp4':'video/mp4','.wav':'audio/wav','.mp3':'audio/mpeg','.vtt':'text/vtt'}[ext];assert(mime,'Unsupported embedded asset extension: '+ext);content=content.split('{{asset:'+rel+'}}').join('data:'+mime+';base64,'+data.toString('base64'));}return content;
}
export async function widgetAssets(){const manifest=JSON.parse(await fs.readFile(path.join(ROOT,'assets/media/widget-assets.json'),'utf8'));const out={};for(const [key,a]of Object.entries(manifest)){const data=await fs.readFile(path.join(ROOT,'assets/media',a.file));out[key]=a.text?data.toString('utf8'):`data:${a.mime};base64,${data.toString('base64')}`}return out}
export async function renderCraft(deck,options={}){
 validateCraft(deck,options);const base=options.assetBase||ROOT;
 const css=await fs.readFile(path.join(ROOT,'assets/runtime/player.css'),'utf8'),player=await fs.readFile(path.join(ROOT,'assets/runtime/player.js'),'utf8');
 const width=deck.width||deck.brand?.canvas.width||1280,height=deck.height||deck.brand?.canvas.height||720,language=deck.language||'en',direction=deck.direction||(/^(ar|he|fa|ur)(-|$)/.test(language)?'rtl':'ltr');const labels={};const values=languages[language.split('-')[0]]||languages.en;['prev','next','jump','overview','notes','reset','full'].forEach((k,i)=>labels[k]=values[i]);Object.assign(labels,deck.labels||{});
 const meta={version:3,width,height,title:deck.title,language,direction,readingMode:deck.readingMode||(deck.mode==='workshop'?'reference':'live'),sample:!!deck.sample,mode:deck.mode||'audience',copyRules,slides:deck.slides.map(({id,title,notes='',sources=[],exportPolicy='final',copyWaivers=[],readingMode=deck.readingMode||(deck.mode==='workshop'?'reference':'live'),spaceIntent=''})=>({id,title,notes:options.stripNotes?'':notes,sources,exportPolicy,copyWaivers,readingMode,spaceIntent}))};
 const pages=await Promise.all(deck.slides.map(async s=>`<section class="slide ${h(s.className||'')}" id="${h(s.id)}" role="group" aria-roledescription="slide" aria-label="${h(s.title)}" aria-hidden="true"${s.language?` lang="${h(s.language)}"`:''}${s.direction?` dir="${h(s.direction)}"`:''}>${await embedAssets(s.content,base)}${deck.brand?await embedAssets(brandLogo(deck.brand),base):''}${deck.draft?'<span style="position:absolute;right:20px;top:10px;background:#ffda70;color:#111;padding:8px;font:18px sans-serif">DRAFT</span>':''}</section>`));
 const btn=(id,label,body=label,extra='')=>`<button id="studio-${id}" type="button" aria-label="${h(label)}" ${extra}>${h(body)}</button>`;
 const controls=btn('prev',labels.prev,'←')+'<span id="studio-position" class="studio-position"></span>'+btn('next',labels.next,'→')+`<select id="studio-jump" aria-label="${h(labels.jump)}">`+deck.slides.map((s,i)=>`<option value="${i}">${i+1}. ${h(s.title)}</option>`).join('')+'</select>'+btn('overview',labels.overview)+btn('notes-btn',labels.notes,labels.notes,'aria-expanded="false" aria-controls="studio-notes"')+btn('reset',labels.reset)+btn('full',labels.full);
 let custom=deck.script||'';const configs=deck.slides.flatMap(s=>s.widgets||[]);
 if(configs.length){const [mesh,widgets,assets]=await Promise.all([fs.readFile(path.join(ROOT,'assets/runtime/mesh.js'),'utf8'),fs.readFile(path.join(ROOT,'assets/runtime/widgets.js'),'utf8'),widgetAssets()]);custom=mesh+'\n'+widgets+'\nmountStudioWidgets('+await embedAssets(json(configs),base)+','+json(assets)+');\n'+custom;}
 const styles=await embedAssets((deck.brand?brandCSS(deck.brand)+'\n':'')+(deck.css||''),base);new vm.Script(player);if(custom)new vm.Script(custom);
 return `<!doctype html><html lang="${h(language)}" dir="${direction}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="generator" content="Slide Studio 3.4.0"><title>${h(deck.title)}</title><style>${css}\n:root{--studio-w:${width}px;--studio-h:${height}px;--studio-ratio:${width}/${height}}@media print{@page{size:${width/96}in ${height/96}in}}\n${styles}</style></head><body><main class="studio-stage">${pages.join('\n')}</main><nav class="studio-controls" aria-label="${h(labels.jump)}">${controls}</nav><aside id="studio-notes" class="studio-notes" aria-label="${h(labels.notes)}"></aside><div id="studio-announcer" class="sr-only studio-announcer" aria-live="polite"></div><script type="application/json" id="slide-studio-meta">${json(meta)}</script><script>${player}</script>${custom?'<script>'+custom.replace(/<\/script/gi,'<\\/script')+'</script>':''}</body></html>`;
}
