/** Self-contained HTML player. Navigation is progressive, never autoplay.
 * Print/export reveals every build. Author notes remain outside slide elements.
 */
import {esc,safeJSON} from './core.mjs';
export function nodeHTML(n){const p=`left:${n.x}px;top:${n.y}px;width:${n.w}px;height:${n.h}px;`;let html;
 if(n.type==='text')html=`<div class="node text" data-id="${esc(n.id)}" data-step="${n.step}" style="${p}font:${n.weight} ${n.size}px/${n.lineHeight} '${esc(n.font)}',sans-serif;color:${n.color};text-align:${n.align}">${esc(n.text)}</div>`;
 else if(n.type==='line'){const x1=n.x1??n.x,y1=n.y1??n.y,x2=n.x2??n.x+n.w,y2=n.y2??n.y+n.h;html=`<svg class="node" data-id="${esc(n.id)}" data-step="${n.step}" style="left:0;top:0;width:1280px;height:720px;overflow:visible;pointer-events:none" aria-hidden="true"><line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${n.stroke}" stroke-width="${n.strokeWidth}"/></svg>`;}
 else if(n.type==='image'||n.type==='svg')html=`<img class="node" data-id="${esc(n.id)}" data-step="${n.step}" src="${esc(n.src)}" alt="${esc(n.alt||'') }" style="${p}object-fit:${n.fit||'contain'}">`;
 else html=`<div class="node" data-id="${esc(n.id)}" data-step="${n.step}" aria-hidden="true" style="${p}background:${n.fill};border:${n.strokeWidth}px solid ${n.stroke};border-radius:${n.type==='ellipse'?'50%':(n.radius||0)+'px'}"></div>`;
 return html;
}
export function renderHTML(scene){return `<!doctype html>
<html lang="${esc(scene.language)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(scene.title)}</title><style>
*{box-sizing:border-box}body{margin:0;background:#15171b;font-family:Arial,sans-serif;color:white}.viewport{width:100vw;height:100vh;display:grid;place-items:center}.deck{width:1280px;height:720px;position:relative;transform-origin:center}.slide{display:none;position:absolute;inset:0;overflow:hidden}.slide.active{display:block}.node{position:absolute;margin:0}.text{white-space:pre;overflow:visible}.slide .node{transition:opacity .28s ease,translate .28s ease}.slide .node.hidden-build{opacity:0;translate:0 14px;visibility:hidden}body.static .node{opacity:1!important;translate:none!important;visibility:visible!important;transition:none!important}nav{position:fixed;bottom:12px;left:50%;transform:translateX(-50%);display:flex;gap:10px;padding:8px;border-radius:8px;background:#15171bdb;opacity:.15;transition:opacity .2s}nav:hover,nav:focus-within{opacity:1}button{font:14px Arial;color:white;background:transparent;border:1px solid #6d737f;border-radius:5px;padding:7px 12px;cursor:pointer}button:focus-visible{outline:3px solid #95c6ff;outline-offset:2px}.counter{display:grid;place-items:center;min-width:75px;font-size:13px}.notes{display:none;position:fixed;right:20px;top:20px;max-width:540px;max-height:75vh;overflow:auto;background:#fff;color:#20242c;padding:24px;font:18px/1.6 Arial;border-radius:10px;white-space:pre-wrap;box-shadow:0 6px 40px #0004}.notes.open{display:block}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}
body.overview{overflow:auto}body.overview .viewport{display:block;width:auto;height:auto;padding:24px}body.overview .deck{transform:none!important;width:auto;height:auto;display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,358px),1fr));gap:20px}body.overview .slide{display:block;position:relative;width:1280px;height:720px;zoom:.28;transform:none;transform-origin:top left;margin:0}body.overview .node{opacity:1!important;visibility:visible!important;translate:none!important}body.overview nav{opacity:1}
@media(prefers-reduced-motion:reduce){.slide .node{transition:none;translate:none!important}}
@page{size:13.333333in 7.5in;margin:0}@media print{html,body{width:1280px;background:white;margin:0;-webkit-print-color-adjust:exact;print-color-adjust:exact}.viewport{display:block;width:1280px;height:auto}.deck{transform:none!important;width:1280px;height:auto}.slide{display:block!important;position:relative!important;width:1280px;height:720px;break-after:page;page-break-after:always}.slide:last-child{break-after:auto;page-break-after:auto}.node{opacity:1!important;visibility:visible!important;translate:none!important;transition:none!important}nav,.notes,.sr-only{display:none!important}body.overview .deck{display:block}body.overview .slide{transform:none;zoom:1;margin:0}}
</style></head><body><div class="viewport"><main class="deck" aria-label="${esc(scene.title)}">${scene.slides.map((s,i)=>`<section class="slide${i===0?' active':''}" id="${esc(s.id)}" aria-label="${esc(s.title)}" aria-hidden="${i!==0}" style="background:${s.paper}">${s.elements.map(nodeHTML).join('')}</section>`).join('\n')}</main></div><nav aria-label="スライド操作"><button id="prev" aria-label="前へ">←</button><span class="counter"></span><button id="next" aria-label="次へ">→</button><button id="overview">一覧 O</button><button id="notes">ノート N</button><button id="full">全画面 F</button></nav><aside class="notes" aria-label="発表者ノート"></aside><div class="sr-only" aria-live="polite" id="announce"></div>
<!-- Canonical scene for EDITABLE export; keep this JSON synchronized by rebuilding.
     Arbitrary DOM/CSS edits do not update PPTX scene objects. Use fidelity export for them. -->
<script type="application/json" id="slide-studio-scene">${safeJSON(scene)}</script>
<script>
(()=>{'use strict';const scene=JSON.parse(document.getElementById('slide-studio-scene').textContent);const slides=[...document.querySelectorAll('.slide')];let current=0,step=0;const params=new URLSearchParams(location.search);if(params.has('static'))document.body.classList.add('static');
const maxBuild=i=>Math.max(0,...scene.slides[i].elements.map(n=>n.step||0));
function scale(){document.querySelector('.deck').style.transform='scale('+Math.min(innerWidth/1280,innerHeight/720)+')'}
function show(i,build=0){current=Math.max(0,Math.min(slides.length-1,i));step=Math.max(0,Math.min(maxBuild(current),build));slides.forEach((s,j)=>{s.classList.toggle('active',j===current);s.setAttribute('aria-hidden',!document.body.classList.contains('overview')&&j!==current);s.querySelectorAll('[data-step]').forEach(n=>n.classList.toggle('hidden-build',Number(n.dataset.step)>step))});document.querySelector('.counter').textContent=(current+1)+' / '+slides.length;const note=scene.slides[current];document.querySelector('.notes').textContent=note.notes+(note.sources.length?'\\n\\nSources\\n'+note.sources.map(s=>typeof s==='string'?s:(s.title||'Source')+' '+(s.url||s.file||'')).join('\\n'):'');document.getElementById('announce').textContent=note.title;history.replaceState(null,'','#'+encodeURIComponent(note.id));}
function next(){if(!document.body.classList.contains('static')&&step<maxBuild(current))show(current,step+1);else if(current<slides.length-1)show(current+1)}
function prev(){if(step>0&&!document.body.classList.contains('static'))show(current,step-1);else if(current>0)show(current-1,maxBuild(current-1))}
function overview(){const on=document.body.classList.toggle('overview');slides.forEach((s,i)=>s.setAttribute('aria-hidden',!on&&i!==current));scale()}
function notes(){document.querySelector('.notes').classList.toggle('open')}
async function full(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{document.getElementById('announce').textContent='全画面表示はこの環境では利用できません'}}
document.getElementById('next').onclick=next;document.getElementById('prev').onclick=prev;document.getElementById('overview').onclick=overview;document.getElementById('notes').onclick=notes;document.getElementById('full').onclick=full;
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();next()}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();prev()}else if(e.key==='Home'){e.preventDefault();show(0)}else if(e.key==='End'){e.preventDefault();show(slides.length-1,maxBuild(slides.length-1))}else if(e.key.toLowerCase()==='o')overview();else if(e.key.toLowerCase()==='n')notes();else if(e.key.toLowerCase()==='f')full();else if(e.key==='Escape'){document.body.classList.remove('overview');document.querySelector('.notes').classList.remove('open');show(current,step)}});
window.addEventListener('resize',scale);window.addEventListener('beforeprint',()=>document.body.classList.add('printing'));window.addEventListener('afterprint',()=>document.body.classList.remove('printing'));
// Deliberately tiny automation interface; renderers need no synthetic keyboard events.
window.slideStudio={scene,show,showAllBuilds:()=>{document.body.classList.add('static');show(current,maxBuild(current))},getState:()=>({current,step,maxBuild:maxBuild(current)})};
let hash;try{hash=decodeURIComponent(location.hash.slice(1))}catch{hash=''}const start=scene.slides.findIndex(s=>s.id===hash);scale();show(start>=0?start:0);})();
</script></body></html>`;}
