#!/usr/bin/env node
/** Small-model path: edit a deck JSON, run validate, build, inspect, export.
 * Paths are resolved from the invocation directory; image paths from the deck file.
 * Commands never overwrite existing output without --force. */
import fs from 'node:fs/promises';import path from 'node:path';import vm from 'node:vm';
import {ROOT,LAYOUTS,loadTheme,compile,embedAssets,assert} from './core.mjs';import {renderHTML} from './html.mjs';
const args=process.argv.slice(2),cmd=args.shift();
const value=k=>{const i=args.indexOf(k);return i<0?undefined:args[i+1]};
async function write(file,data){await fs.mkdir(path.dirname(path.resolve(file)),{recursive:true});await fs.writeFile(file,data,{flag:args.includes('--force')?'w':'wx'})}
try{
 if(cmd==='list'){console.log(JSON.stringify({layouts:LAYOUTS,themes:(await fs.readdir(path.join(ROOT,'assets/themes'))).filter(x=>x.endsWith('.json')).map(x=>x.slice(0,-5))},null,2));}
 else if(cmd==='init'){const out=args[0];assert(out,'init OUTPUT_DIRECTORY [--example executive|talk|casual|technical|editorial|training]');const example=value('--example')||'executive';assert(/^[a-z-]+$/.test(example),'invalid example');await fs.mkdir(out,{recursive:true});await write(path.join(out,'deck.json'),await fs.readFile(path.join(ROOT,'assets/examples',example+'.json')));console.log(path.resolve(out,'deck.json'));}
 else if(cmd==='build'||cmd==='validate'){const file=args[0];assert(file,'specify deck.json');let spec=JSON.parse(await fs.readFile(file,'utf8'));let selected=value('--theme')||spec.theme||'neutral';if(typeof selected==='string'&&selected.endsWith('.json')&&!value('--theme'))selected=path.resolve(path.dirname(file),selected);const theme=await loadTheme(selected);let scene=compile(spec,theme);scene=await embedAssets(scene,path.dirname(path.resolve(file)));if(cmd==='build'){const out=value('--out');assert(out,'build requires --out deck.html');assert(/\.html?$/i.test(out),'output must end in .html');const html=renderHTML(scene);for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);if(!args.includes('--force'))for(const dest of [out,out.replace(/\.html?$/i,'')+'.scene.json']){try{await fs.access(dest);throw Error('Output exists: '+dest)}catch(e){if(e.code!=='ENOENT')throw e}}await write(out,html);await write(out.replace(/\.html?$/i,'')+'.scene.json',JSON.stringify(scene,null,2));console.log(JSON.stringify({html:path.resolve(out),slides:scene.slides.length,warnings:scene.warnings},null,2))}else console.log(JSON.stringify({valid:true,slides:scene.slides.length,warnings:scene.warnings},null,2));}
 else if(cmd==='brand'){const name=args[0],out=value('--out');assert(name&&out,'brand NAME --out theme.json [--base neutral]');const t=await loadTheme(value('--base')||'neutral');delete t.muted;delete t.line;delete t.tint;t.name=name;t.brand={status:'draft',source:'User-approved reference needed',rules:['Use approved logo files without redrawing','Keep reference layout proportions','Review Japanese and Latin font fallbacks']};await write(out,JSON.stringify(t,null,2));console.log(path.resolve(out));}
 else console.log('Slide Studio\n  list\n  init OUTPUT_DIR [--example executive]\n  validate deck.json [--theme NAME]\n  build deck.json --out deck.html [--theme NAME] [--force]\n  brand NAME --out theme.json [--base neutral]\nSee references/exports.md for PDF/PPTX and browser QA.');
}catch(e){console.error('Slide Studio:',e.message);process.exitCode=1}
